# Generated by Django 3.0.8 on 2020-07-22 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov_knjige', models.CharField(max_length=100)),
                ('ime_pisca', models.CharField(max_length=100)),
                ('prezime_pisca', models.CharField(max_length=100)),
                ('jezik', models.CharField(max_length=100)),
                ('pismo', models.CharField(max_length=100)),
                ('velicina', models.CharField(max_length=100)),
                ('dostupno', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
